apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account-service
        image: drjoelkoh/account-service:latest
        ports:
          - containerPort: 5000
        env:
          - name: ACCOUNT_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: account-db-secret
                key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP