apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 2  # You can adjust this based on the load
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: drjoelkoh/api-gateway:latest
        ports:
        - containerPort: 8080  # Replace with your API Gateway’s exposed port
        env:
        - name: USER_TOKEN_SECRET_KEY
          value: "kZFEWrVY9qLGCAB"
        - name: ACCOUNT_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: account-db-secret
              key: DATABASE_URL
        - name: TRANSACTION_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: transaction-db-secret
              key: DATABASE_URL
        - name: TRIP_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: trip-db-secret
              key: DATABASE_URL
        - name: VISION_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: vision-db-secret
              key: DATABASE_URL
        - name: ACCOUNT_SERVICE_ADDRESS
          value: "account-service:80"
        - name: TRANSACTION_SERVICE_ADDRESS
          value: "transaction-service:80"
        - name: TRIP_SERVICE_ADDRESS
          value: "trip-service:80"
        - name: VISION_SERVICE_ADDRESS
          value: "vision-service:80"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway  
  type: NodePort
  ports:
  - protocol: TCP
    port: 80  
    targetPort: 8080 
    nodePort: 32080
  