apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 2  # You can adjust this based on the load
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: your-docker-username/api-gateway:latest
        ports:
        - containerPort: 8080  # Replace with your API Gateway’s exposed port
        env:
        - name: ACCOUNT_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: account-db-secret
              key: DATABASE_URL
        - name: TRANSACTION_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: transaction-db-secret
              key: DATABASE_URL
        - name: TRIP_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: trip-db-secret
              key: DATABASE_URL
        - name: VISION_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: vision-db-secret
              key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-loadbalancer
spec:
  selector:
    app: api-gateway  # This label should match the label in your deployment
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80  # External port for users to access the gateway
    targetPort: 8080  # Port the gateway container is listening on
  sessionAffinity: ClientIP  # Optional: Use this for session persistence
