apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
      - name: transaction-service
        image: drjoelkoh/transaction-service:latest
        ports:
          - containerPort: 5001
        env:
          - name: TRANSACTION_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: transaction-db-secret
                key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  selector:
    app: transaction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP