apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
      - name: transaction-service
        image: your-docker-username/transaction-service:latest
        ports:
          - containerPort: 5001
        env:
          - name: postgres://avnadmin:AVNS_rOO_xCE2pecb4TH8FOY@cloudmrt-cloudmrt.j.aivencloud.com:19275/transactionDB?sslmode=require
            valueFrom:
              secretKeyRef:
                name: transaction-db-url
                key: postgres://avnadmin:AVNS_rOO_xCE2pecb4TH8FOY@cloudmrt-cloudmrt.j.aivencloud.com:19275/transactionDB?sslmode=require
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  selector:
    app: transaction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP