apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trip
  template:
    metadata:
      labels:
        app: trip
    spec:
      containers:
      - name: trip-service
        image: kuanyong652/trip-service:latest
        ports:
          - containerPort: 50053
        env:
          - name: TRIP_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: trip-db-secret
                key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: trip-service
spec:
  selector:
    app: trip
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50053
  type: ClusterIP