apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trip
  template:
    metadata:
      labels:
        app: trip
    spec:
      containers:
      - name: trip-service
        image: your-docker-username/trip-service:latest
        ports:
          - containerPort: 5002
        env:
          - name: postgres://avnadmin:AVNS_rOO_xCE2pecb4TH8FOY@cloudmrt-cloudmrt.j.aivencloud.com:19275/tripDB?sslmode=require
            valueFrom:
              secretKeyRef:
                name: trip-db-url
                key: postgres://avnadmin:AVNS_rOO_xCE2pecb4TH8FOY@cloudmrt-cloudmrt.j.aivencloud.com:19275/tripDB?sslmode=require
---
apiVersion: v1
kind: Service
metadata:
  name: trip-service
spec:
  selector:
    app: trip
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: ClusterIP