apiVersion: apps/v1
kind: Deployment
metadata:
  name: vision-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vision
  template:
    metadata:
      labels:
        app: vision
    spec:
      containers:
      - name: vision-service
        image: your-docker-username/vision-service:latest
        ports:
          - containerPort: 5003
        env:
          - name: postgres://avnadmin:AVNS_rOO_xCE2pecb4TH8FOY@cloudmrt-cloudmrt.j.aivencloud.com:19275/visionDB?sslmode=require
            valueFrom:
              secretKeyRef:
                name: vision-db-url
                key: postgres://avnadmin:AVNS_rOO_xCE2pecb4TH8FOY@cloudmrt-cloudmrt.j.aivencloud.com:19275/visionDB?sslmode=require
---
apiVersion: v1
kind: Service
metadata:
  name: vision-service
spec:
  selector:
    app: vision
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
  type: ClusterIP