apiVersion: apps/v1
kind: Deployment
metadata:
  name: vision-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vision
  template:
    metadata:
      labels:
        app: vision
    spec:
      containers:
      - name: vision-service
        image: drjoelkoh/vision-service:latest
        ports:
          - containerPort: 5003
        env:
          - name: VISION_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: vision-db-secret
                key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: vision-service
spec:
  selector:
    app: vision
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
  type: ClusterIP